# ZHVI Time Series Data from Zillow Research Preprocessing and Preparation for ARIMA Model

In [1]:
import pandas as pd

In [2]:
'''
Combined data frame of ZHVI Time Series Data from Zillow Research

Link: https://www.zillow.com/research/data/

Datasets/CSV used:

ZHVI 1-Bedroom Time Series ($) Geography: Zip

ZHVI 2-Bedroom Time Series ($) Geography: Zip

ZHVI 3-Bedroom Time Series ($) Geography: Zip

ZHVI 4-Bedroom Time Series ($) Geography: Zip

ZHVI 5+-Bedroom Time Series ($) Geography: Zip
'''
zhvi_ts = pd.read_csv("./data/zillow_zhvi_time_series_brdmcnt1_5.csv")

In [3]:
zhvi_ts.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30,2024-05-31,2024-06-30,BedroomCount
0,61148,2,8701,zip,NJ,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,46836.396484,...,141497.665278,143634.490894,146004.164449,148087.619189,149561.027992,151039.984251,152681.854404,154681.744325,156591.870296,1
1,62080,4,11368,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,NaN,...,310150.032720,309533.173937,307535.802144,306263.410187,305841.928108,308115.982384,310365.348214,312972.679906,313353.477013,1
2,91733,5,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,NaN,...,117503.733918,116916.403287,116134.156800,115565.348920,114702.774216,113793.267769,112837.304225,112265.974667,111931.304704,1
3,62093,7,11385,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,NaN,...,534154.046583,533319.993664,532294.619178,532835.569826,530775.126698,531709.481705,531540.510245,533583.407177,531158.192879,1
4,95992,10,90011,zip,CA,CA,Los Angeles,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,72077.898597,...,482421.949397,485277.821349,486299.210100,483871.805337,477368.673174,470516.381584,466785.165013,466186.435756,464923.576361,1

In [4]:
# Selecting Columns
selected_columns = ['RegionName', 'State', 'CountyName', 'BedroomCount', 'City'] + pd.date_range(start='2000-01-31', end='2024-06-30', freq='M').strftime('%Y-%m-%d').tolist()
zhvi_ts = zhvi_ts[selected_columns]
zhvi_ts.rename(columns={'RegionName':'Zip'}, inplace=True)
zhvi_ts.rename(columns={'City':'city'}, inplace=True)

In [5]:
# Backward Fill
zhvi_ts_bf = zhvi_ts.T.fillna(method='bfill').T
zhvi_ts_bf.head()

,Zip,State,CountyName,BedroomCount,city,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30,2024-05-31,2024-06-30
0,8701,NJ,Ocean County,1,Lakewood,46836.396484,46912.963483,47063.362452,47159.254674,47196.113629,...,139852.482501,141497.665278,143634.490894,146004.164449,148087.619189,149561.027992,151039.984251,152681.854404,154681.744325,156591.870296
1,11368,NY,Queens County,1,New York,164335.217348,164335.217348,164335.217348,164335.217348,164335.217348,...,308260.42864,310150.03272,309533.173937,307535.802144,306263.410187,305841.928108,308115.982384,310365.348214,312972.679906,313353.477013
2,77084,TX,Harris County,1,Houston,114919.950559,114919.950559,114919.950559,114919.950559,114919.950559,...,117571.196549,117503.733918,116916.403287,116134.1568,115565.34892,114702.774216,113793.267769,112837.304225,112265.974667,111931.304704
3,11385,NY,Queens County,1,New York,298774.780139,298774.780139,298774.780139,298774.780139,298774.780139,...,537589.010988,534154.046583,533319.993664,532294.619178,532835.569826,530775.126698,531709.481705,531540.510245,533583.407177,531158.192879
4,90011,CA,Los Angeles County,1,Los Angeles,72077.898597,71070.133047,70627.678753,69786.200113,70300.296518,...,479196.694975,482421.949397,485277.821349,486299.2101,483871.805337,477368.673174,470516.381584,466785.165013,466186.435756,464923.576361

In [6]:
'''
US Cities dataset from Simple Maps - Commerical Use

Converted from .xlsx to .csv

Link: https://simplemaps.com/data/us-zips
'''
us_cities = pd.read_csv("./data/uscities.csv")
us_cities.head()

,city,city_ascii,state_id,state_name,county_fips,county_name,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,New York,New York,NY,New York,36081,Queens,40.6943,-73.9249,18908608,11080.3,shape,False,True,America/New_York,1,11229 11228 11226 11225 11224 11222 11221 1122...,1840034016
1,Los Angeles,Los Angeles,CA,California,6037,Los Angeles,34.1141,-118.4068,11922389,3184.7,shape,False,True,America/Los_Angeles,1,91367 90291 90293 90292 91316 91311 90035 9003...,1840020491
2,Chicago,Chicago,IL,Illinois,17031,Cook,41.8375,-87.6866,8497759,4614.5,shape,False,True,America/Chicago,1,60018 60649 60641 60640 60643 60642 60645 6064...,1840000494
3,Miami,Miami,FL,Florida,12086,Miami-Dade,25.7840,-80.2101,6080145,4758.9,shape,False,True,America/New_York,1,33128 33129 33125 33126 33127 33149 33144 3314...,1840015149
4,Houston,Houston,TX,Texas,48201,Harris,29.7860,-95.3885,5970127,1384.0,shape,False,True,America/Chicago,1,77069 77068 77061 77060 77063 77062 77065 7706...,1840020925

In [7]:
# Restructing Data so that 1 zip code per row, selecting columns
us_cities = us_cities.assign(zips=us_cities['zips'].str.split()).explode('zips')
us_cities = us_cities[['zips', 'population', 'density', 'city']]
us_cities.rename(columns={'zips':'Zip'}, inplace=True)
us_cities['Zip'] = us_cities['Zip'].fillna(-1).astype(int)
print(us_cities.shape)
us_cities.head()

(48191, 4)

     Zip  population  density      city
0  11229    18908608  11080.3  New York
0  11228    18908608  11080.3  New York
0  11226    18908608  11080.3  New York
0  11225    18908608  11080.3  New York
0  11224    18908608  11080.3  New York

In [8]:
zhvi_ts_merged = pd.merge(zhvi_ts_bf, us_cities, on=['Zip', 'city'], how='left')
zhvi_ts_merged = zhvi_ts_merged.dropna(how='any')
zhvi_ts_merged.head()

,Zip,State,CountyName,BedroomCount,city,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30,2024-05-31,2024-06-30,population,density
1,11368,NY,Queens County,1,New York,164335.217348,164335.217348,164335.217348,164335.217348,164335.217348,...,309533.173937,307535.802144,306263.410187,305841.928108,308115.982384,310365.348214,312972.679906,313353.477013,18908608.0,11080.3
2,77084,TX,Harris County,1,Houston,114919.950559,114919.950559,114919.950559,114919.950559,114919.950559,...,116916.403287,116134.1568,115565.34892,114702.774216,113793.267769,112837.304225,112265.974667,111931.304704,5970127.0,1384.0
3,11385,NY,Queens County,1,New York,298774.780139,298774.780139,298774.780139,298774.780139,298774.780139,...,533319.993664,532294.619178,532835.569826,530775.126698,531709.481705,531540.510245,533583.407177,531158.192879,18908608.0,11080.3
4,90011,CA,Los Angeles County,1,Los Angeles,72077.898597,71070.133047,70627.678753,69786.200113,70300.296518,...,485277.821349,486299.2101,483871.805337,477368.673174,470516.381584,466785.165013,466186.435756,464923.576361,11922389.0,3184.7
5,90650,CA,Los Angeles County,1,Norwalk,189346.921534,189346.921534,189346.921534,189346.921534,189346.921534,...,434927.156323,437928.189418,439930.166675,439270.397583,438761.126208,437598.729335,437596.809191,436331.683142,101893.0,4052.7

In [9]:
zd_temp = zhvi_ts_merged[zhvi_ts_merged['city'] == 'New York']
zd_temp.head(50)

,Zip,State,CountyName,BedroomCount,city,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30,2024-05-31,2024-06-30,population,density
1,11368,NY,Queens County,1,New York,164335.217348,164335.217348,164335.217348,164335.217348,164335.217348,...,309533.173937,307535.802144,306263.410187,305841.928108,308115.982384,310365.348214,312972.679906,313353.477013,18908608.0,11080.3
3,11385,NY,Queens County,1,New York,298774.780139,298774.780139,298774.780139,298774.780139,298774.780139,...,533319.993664,532294.619178,532835.569826,530775.126698,531709.481705,531540.510245,533583.407177,531158.192879,18908608.0,11080.3
7,11236,NY,Kings County,1,New York,125954.236222,126631.183437,127062.282989,128427.489794,129627.041491,...,348870.77904,346580.908281,346290.487787,346988.184972,349941.463061,352063.370395,354196.442715,354258.212655,18908608.0,11080.3
8,10467,NY,Bronx County,1,New York,93303.806545,93303.806545,93303.806545,93303.806545,93303.806545,...,205846.235566,202536.087869,199592.82274,198626.880607,200917.17977,203842.324706,207148.158026,208500.031903,18908608.0,11080.3
9,11373,NY,Queens County,1,New York,112429.998936,112957.24692,113572.904019,114443.345659,115082.968496,...,348012.702712,343832.685563,342259.086237,341870.808781,344087.395731,345975.285064,348199.124452,348666.159806,18908608.0,11080.3
10,11226,NY,Kings County,1,New York,255335.410372,255335.410372,255335.410372,255335.410372,255335.410372,...,510207.611826,510847.681627,514780.370008,517382.130981,520343.413605,522352.477574,524139.552479,525412.092054,18908608.0,11080.3
11,11207,NY,Kings County,1,New York,185036.657924,185036.657924,185036.657924,185036.657924,185036.657924,...,374085.886234,374212.652774,375219.593691,376367.656268,378783.725838,380591.906099,382159.961071,381527.489194,18908608.0,11080.3
17,10025,NY,New York County,1,New York,184498.567893,186341.769441,188553.731099,193121.749413,197264.137173,...,754841.721269,752028.130195,750653.595304,749054.43975,749455.178939,749820.42332,751401.444538,753786.126932,18908608.0,11080.3
19,11214,NY,Kings County,1,New York,234338.947012,234338.947012,234338.947012,234338.947012,234338.947012,...,353317.122565,350522.48872,350325.022195,351772.554622,355724.043147,359372.837229,362659.690981,364143.341235,18908608.0,11080.3
23,11234,NY,Kings County,1,New York,130461.711024,131314.208468,131960.003428,133252.670673,134384.692747,...,280458.98617,276971.676429,275065.965007,274184.471971,275148.446491,276131.210325,276883.840176,276681.014927,18908608.0,11080.3
25,10314,NY,Richmond County,1,New York,93540.993463,94232.915471,94827.689534,95897.660086,96863.50722,...,344719.405105,344464.28077,345666.811674,347819.285398,350113.716491,351393.635448,351629.118141,351514.360877,18908608.0,11080.3
26,11220,NY,Kings County,1,New York,356906.074263,356906.074263,356906.074263,356906.074263,356906.074263,...,431802.249621,431186.193278,432221.472838,433966.480593,437820.69918,442155.848984,446217.21671,448042.410717,18908608.0,11080.3
29,11206,NY,Kings County,1,New York,372605.865901,372605.865901,372605.865901,372605.865901,372605.865901,...,670883.027656,664176.074998,664282.647465,666899.470764,674858.971674,679881.019849,685416.422886,687886.231029,18908608.0,11080.3
30,11221,NY,Kings County,1,New York,91688.169588,91894.926283,92262.214099,92487.720371,92650.747208,...,620522.820876,612122.731886,608516.059428,607140.710157,611359.369689,615116.108098,619540.537176,618813.6682,18908608.0,11080.3
34,11223,NY,Kings County,1,New York,238189.294162,238189.294162,238189.294162,238189.294162,238189.294162,...,338125.150951,332744.36352,329912.931082,329094.711515,330911.761812,333014.033701,336391.796217,338252.114421,18908608.0,11080.3
36,11230,NY,Kings County,1,New York,251975.066987,251975.066987,251975.066987,251975.066987,251975.066987,...,340311.073105,337758.316958,338044.318351,339383.273645,342412.965393,344928.677187,347440.18256,348598.685881,18908608.0,11080.3
39,10458,NY,Bronx County,1,New York,109307.677201,109307.677201,109307.677201,109307.677201,109307.677201,...,200606.861142,197707.460675,196012.644515,196448.960055,199718.196626,203543.635875,207971.378221,208486.972873,18908608.0,11080.3
40,11377,NY,Queens County,1,New York,128263.568353,128263.568353,128263.568353,128263.568353,128263.568353,...,357174.073127,356452.968419,357845.351179,358856.587719,362225.804076,364773.398215,367306.374173,367493.674664,18908608.0,11080.3
45,11235,NY,Kings County,1,New York,92351.863861,92878.986476,93290.240361,94181.438404,95253.049018,...,315842.93711,314670.953804,316102.326567,318671.369719,322502.916207,325440.441086,327900.000582,329021.590504,18908608.0,11080.3
46,11229,NY,Kings County,1,New York,160751.099971,160751.099971,160751.099971,160751.099971,160751.099971,...,281135.580477,278702.344962,277946.866029,278191.401252,280321.194225,282144.438334,284005.475977,284890.565327,18908608.0,11080.3
47,11233,NY,Kings County,1,New York,106628.477773,107519.622228,108521.340971,109373.02901,110016.545994,...,556115.599444,553844.614879,557342.668288,560481.140779,564656.18059,566989.166639,571101.374834,571584.238673,18908608.0,11080.3
50,11204,NY,Kings County,1,New York,370399.674838,370399.674838,370399.674838,370399.674838,370399.674838,...,454339.1359,449525.173265,447710.459953,448711.03886,454307.905856,460843.774032,467535.336094,469206.731614,18908608.0,11080.3
51,10468,NY,Bronx County,1,New York,140557.416938,140557.416938,140557.416938,140557.416938,140557.416938,...,198565.223272,195998.631921,194989.523503,195701.879051,198381.320375,200925.835192,202991.964632,202035.253585,18908608.0,11080.3
56,11355,NY,Queens County,1,New York,142859.889108,143205.303111,143913.595079,145052.18608,146054.794563,...,418843.309606,417539.854985,418024.875444,419611.86475,422702.152381,425269.521059,427424.240895,428138.333152,18908608.0,11080.3
58,11203,NY,Kings County,1,New York,311226.517225,311226.517225,311226.517225,311226.517225,311226.517225,...,386445.399016,383719.963997,382071.565493,381841.910272,384577.573409,388075.202851,391631.176122,391443.228653,18908608.0,11080.3
62,10457,NY,Bronx County,1,New York,105833.808335,105833.808335,105833.808335,105833.808335,105833.808335,...,206540.993187,207341.66851,205928.97346,205991.798705,211048.459279,215633.914974,220351.332544,219644.580115,18908608.0,11080.3
69,10029,NY,New York County,1,New York,404612.357452,404612.357452,404612.357452,404612.357452,404612.357452,...,594434.011406,590999.972822,588311.401056,587156.375904,588975.377935,589994.395205,589758.281467,587678.902959,18908608.0,11080.3
71,11218,NY,Kings County,1,New York,283938.202955,283938.202955,283938.202955,283938.202955,283938.202955,...,491742.738805,488314.016804,488650.692901,489681.723983,492884.190546,495177.25726,497627.244098,499764.612078,18908608.0,11080.3
72,10462,NY,Bronx County,1,New York,47831.819187,47851.958555,47952.149661,48256.016717,48775.910404,...,195798.321717,196721.420001,198219.45115,199648.48182,201551.537153,203503.428455,204788.476016,205207.031531,18908608.0,11080.3
78,10002,NY,New York County,1,New York,479904.445042,479904.445042,479904.445042,479904.445042,479904.445042,...,737605.902009,728984.60119,723709.441088,719128.330018,717984.163351,716853.284743,717415.464575,717562.25663,18908608.0,11080.3
79,11375,NY,Queens County,1,New York,152601.910906,152868.66325,153751.492186,154648.753465,155661.360075,...,328714.347028,326131.244683,325223.821438,325746.871296,327915.50785,329957.063701,331499.475475,331559.304212,18908608.0,11080.3
96,11215,NY,Kings County,1,New York,204375.836025,206101.873681,208244.396888,212650.850277,217141.482586,...,803425.741739,798217.445157,797922.574113,797260.4032,799714.97493,801566.232427,806275.064585,811153.861207,18908608.0,11080.3
102,10463,NY,Bronx County,1,New York,211214.178988,211214.178988,211214.178988,211214.178988,211214.178988,...,243291.246622,242274.937776,243329.68605,245301.243972,248149.282515,250423.33688,252028.991929,252862.569603,18908608.0,11080.3
105,11209,NY,Kings County,1,New York,164928.102395,165412.178282,166021.234807,167516.786397,169317.738315,...,345729.506815,343825.094769,344153.520978,345464.912378,348134.181761,350154.780729,351702.175761,351907.83892,18908608.0,11080.3
121,11213,NY,Kings County,1,New York,445819.140836,445819.140836,445819.140836,445819.140836,445819.140836,...,466348.623524,466750.046189,470131.702663,472005.078074,476110.926218,480211.64603,487300.931414,489336.694942,18908608.0,11080.3
125,11201,NY,Kings County,1,New York,263302.641165,264528.404564,265831.169826,266307.56072,266851.031947,...,836310.874705,830599.883664,832573.96442,835831.230422,841451.765919,843579.809448,846449.672717,849217.650389,18908608.0,11080.3
141,11210,NY,Kings County,1,New York,166186.573877,166186.573877,166186.573877,166186.573877,166186.573877,...,294074.482351,292957.239372,294104.80412,295822.764647,299006.648263,301618.494588,304081.80091,304753.967529,18908608.0,11080.3
146,11372,NY,Queens County,1,New York,111985.618045,111927.162862,112628.12473,113687.068846,115253.123026,...,338546.502725,338464.272788,340081.218496,341742.979958,344973.881574,347706.262254,350272.066573,350768.762787,18908608.0,11080.3
148,11432,NY,Queens County,1,New York,227254.309952,227254.309952,227254.309952,227254.309952,227254.309952,...,212621.236474,209997.688359,209271.154168,209364.750514,211842.286069,214136.463943,216294.432655,217319.748577,18908608.0,11080.3
149,10027,NY,New York County,1,New York,376590.678089,376590.678089,376590.678089,376590.678089,376590.678089,...,660693.119318,657640.1944,655892.38913,653818.93407,653930.234853,653482.553796,653850.669847,651529.640687,18908608.0,11080.3
167,11211,NY,Kings County,1,New York,431955.774215,431955.774215,431955.774215,431955.774215,431955.774215,...,905424.779029,902749.174599,906570.873949,910018.062364,915989.962539,917534.638481,918654.34517,917237.747901,18908608.0,11080.3
170,10312,NY,Richmond County,1,New York,127068.954601,128270.456027,128722.330496,129919.22091,130779.881119,...,490398.667241,490894.290935,492369.574119,493576.442522,494906.349351,495526.749889,496897.760301,496453.350962,18908608.0,11080.3
204,10024,NY,New York County,1,New York,277462.932646,281062.939775,283983.015552,290674.523839,297174.419571,...,834557.581451,830289.557219,828183.062226,825104.146778,826659.240123,827414.064124,832470.916845,838375.578987,18908608.0,11080.3
214,10032,NY,New York County,1,New York,420978.039387,420978.039387,420978.039387,420978.039387,420978.039387,...,465601.570985,464550.966226,463337.719334,462429.647355,464775.18362,465993.53519,466930.448138,465299.82347,18908608.0,11080.3
222,11216,NY,Kings County,1,New York,86334.350406,87029.78093,87585.351385,89263.13207,90842.67116,...,723296.889885,713698.836637,710493.085908,712135.649782,718416.144619,720974.67138,723744.006517,720794.209581,18908608.0,11080.3
228,10023,NY,New York County,1,New York,329850.983162,332053.767957,334339.113559,339217.983758,346015.21115,...,918363.07424,910153.151333,907457.682147,903592.332576,903799.738584,904200.959413,909617.862553,916340.352725,18908608.0,11080.3
240,10033,NY,New York County,1,New York,405438.529538,405438.529538,405438.529538,405438.529538,405438.529538,...,478962.8174,476039.862309,475253.438043,474822.036102,475761.418054,475983.796082,476797.738435,477779.239524,18908608.0,11080.3
243,11238,NY,Kings County,1,New York,167976.537112,169577.598382,170854.767698,173558.246653,175779.119568,...,781811.228717,778501.146129,780890.677032,784262.504729,789788.009264,793039.707349,798075.471847,802191.752576,18908608.0,11080.3
252,11435,NY,Queens County,1,New York,176289.834786,176289.834786,176289.834786,176289.834786,176289.834786,...,239013.714487,236993.203734,235287.622304,235114.024864,235939.277628,237250.415739,238427.148185,236971.736929,18908608.0,11080.3
261,10031,NY,New York County,1,New York,276058.438738,276058.438738,276058.438738,276058.438738,276058.438738,...,442437.982983,440431.0511,439386.901879,439326.638204,442194.841187,444692.791588,447215.518167,447800.373657,18908608.0,11080.3

In [10]:
# Reordering Columns
all_columns = zhvi_ts_merged.columns.tolist()
front_columns = ['Zip','State','CountyName','BedroomCount','population', 'density', 'city']
date_columns = [col for col in all_columns if col not in front_columns]
new_order = front_columns + date_columns
zhvi_ts_merged_reordered = zhvi_ts_merged[new_order]
zhvi_ts_merged_reordered.head()

,Zip,State,CountyName,BedroomCount,population,density,city,2000-01-31,2000-02-29,2000-03-31,...,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30,2024-05-31,2024-06-30
1,11368,NY,Queens County,1,18908608.0,11080.3,New York,164335.217348,164335.217348,164335.217348,...,308260.42864,310150.03272,309533.173937,307535.802144,306263.410187,305841.928108,308115.982384,310365.348214,312972.679906,313353.477013
2,77084,TX,Harris County,1,5970127.0,1384.0,Houston,114919.950559,114919.950559,114919.950559,...,117571.196549,117503.733918,116916.403287,116134.1568,115565.34892,114702.774216,113793.267769,112837.304225,112265.974667,111931.304704
3,11385,NY,Queens County,1,18908608.0,11080.3,New York,298774.780139,298774.780139,298774.780139,...,537589.010988,534154.046583,533319.993664,532294.619178,532835.569826,530775.126698,531709.481705,531540.510245,533583.407177,531158.192879
4,90011,CA,Los Angeles County,1,11922389.0,3184.7,Los Angeles,72077.898597,71070.133047,70627.678753,...,479196.694975,482421.949397,485277.821349,486299.2101,483871.805337,477368.673174,470516.381584,466785.165013,466186.435756,464923.576361
5,90650,CA,Los Angeles County,1,101893.0,4052.7,Norwalk,189346.921534,189346.921534,189346.921534,...,425048.660196,430302.238712,434927.156323,437928.189418,439930.166675,439270.397583,438761.126208,437598.729335,437596.809191,436331.683142

In [11]:
# Save csv for ARIMA Model
zhvi_ts_merged_reordered.to_csv("data/zhvi_bdrmcnt_labeled.csv", index=False)